apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wprvm6laj-nodejs 
  janus-idp.io/tekton: wprvm6laj-nodejs
  backstage.io/kubernetes-id: wprvm6laj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wprvm6laj-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml